// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vofpxdbtyfidqsdwwkch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZnB4ZGJ0eWZpZHFzZHd3a2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjYzNzQsImV4cCI6MjA2NDkwMjM3NH0.Vm2atl01Oa73RhRPHmOBARDUZqtT5GqUJtuHA7FbFCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);